import Head from 'next/head'
import {NavigationBar,Hero,Personal,Business,LiveBetter,CardFees,Footer, CardFeatures} from '../components';
import styles from "./style";




export default function Home() {
  return (
    <div className="w-full overflow-hidden">
      <Head>
        <title>Capitec Bank</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={`${styles.paddingX} ${styles.flexCenter}`}>
        <div className={`${styles.boxWidth}`}>
          <NavigationBar/>
        </div>
      </div>

      <div className={`${styles.flexStart}`}>
        <div className={`${styles.boxWidth}`}>
          <Hero />
        </div>
      </div>

            {/* main */}
            <div className={`${styles.paddingX} ${styles.flexStart}`}>
        <div className={`${styles.boxWidth}`}>
          {/* <Statistics /> */}
          <Personal />
          <Business/>
          <LiveBetter/>
          <CardFees/>
          <CardFeatures/>
          <Footer/>

        </div>
      </div>


    </div>
  )
}
